// File: src/services/productionHarvestService.js - Handles all API interactions for Production Harvest Records

import ApiService from './ApiService';
import AsyncStorage from "@react-native-async-storage/async-storage";
import { logProductionHarvestCreated, logSyncCompleted } from './ActivityService';
import { addSyncLog, printSyncLogs } from './SyncLogService';

const SYNC_QUEUE_KEY = "production_harvests_sync_queue"; // Key for the local queue of unsynced production records

// --- Internal Data Mapping (for POST) ---

/**
 * Maps the UI payload (camelCase, internal flags) to the format expected by the backend API (snake_case, strings).
 *
 * API Schema POST: {
 *   "harvest_id": "string",  (REQUIRED - generated by frontend, offline-first)
 *   "worker_name": "string",
 *   "block_id": "string",
 *   "weight_on_delivery": decimal,
 *   "date_of_delivery": "string",
 *   "amount_paid": decimal,
 *   "paid_by": "string"
 * }
 *
 * NOTE: harvest_id MUST be sent on POST - generated by frontend, backend accepts it (offline-first approach)
 *
 * @param {object} payload - The raw payload from the UI or the sync queue.
 * @param {boolean} isUpdate - Whether this is an update operation (includes harvest_id)
 * @returns {object} The API-ready payload.
 */
const mapToApiPayload = (payload, isUpdate = false) => {
    const apiPayload = {};

    // 0. Harvest ID (UI: generatedId/id/harvest_id -> API: harvest_id) - REQUIRED for offline-first
    apiPayload.harvest_id = payload.generatedId || payload.id || payload.harvest_id || '';

    // 1. Worker Name (UI: workerName/worker_name/name -> API: worker_name)
    apiPayload.worker_name = payload.workerName || payload.worker_name || payload.name || '';

    // 2. Block ID (UI: blockId/block_id/block -> API: block_id)
    apiPayload.block_id = payload.blockId || payload.block_id || payload.block || '';

    // 3. Date (UI: date (Date object/ISO string) -> API: date_of_delivery (YYYY-MM-DD string))
    let dateObj = payload.date;
    if (typeof dateObj === 'string') {
        // Convert ISO string (from AsyncStorage) back to a Date object
        dateObj = new Date(dateObj);
    }

    if (dateObj instanceof Date && !isNaN(dateObj)) {
        const year = dateObj.getFullYear();
        const month = String(dateObj.getMonth() + 1).padStart(2, '0');
        const day = String(dateObj.getDate()).padStart(2, '0');
        apiPayload.date_of_delivery = `${year}-${month}-${day}`;
    } else {
        // Fallback for direct date string if parsing failed
        apiPayload.date_of_delivery = payload.date ? payload.date.split('T')[0] : '';
    }

    // 4. Weight (UI: weight (Number) -> API: weight_on_delivery (decimal))
    apiPayload.weight_on_delivery = Number(payload.weight);

    // 5. Amount Paid (UI: amountPaid (Number) -> API: amount_paid (decimal))
    apiPayload.amount_paid = Number(payload.amountPaid || payload.amount_paid || 0);

    // 6. Paid By (UI: paidBy/paid_by/who_paid -> API: paid_by (string))
    if (typeof payload.paidBy === 'object' && payload.paidBy && payload.paidBy.id) {
        apiPayload.paid_by = String(payload.paidBy.id);
    } else if (payload.paidBy) {
        apiPayload.paid_by = String(payload.paidBy);
    } else if (payload.paid_by) {
        apiPayload.paid_by = String(payload.paid_by);
    } else if (payload.who_paid) {
        apiPayload.paid_by = String(payload.who_paid);
    } else {
        apiPayload.paid_by = '';
    }

    return apiPayload;
};

// --- Exported API Functions ---

/**
 * Handles the POST request to create a new Production Harvest record.
 */
export const postProductionHarvestRecord = async (uiPayload) => {
    const apiPayload = mapToApiPayload(uiPayload);
    // Endpoint: harvests/ (production harvests from the harvests app)
    const endpoint = 'harvests/';

    // Debug logging for payload
    console.log('[postProductionHarvestRecord] Original UI payload:', uiPayload);
    console.log('[postProductionHarvestRecord] Mapped API payload:', apiPayload);

    try {
        // Validate API payload before sending (critical check!)
        if (!apiPayload.harvest_id) {
            const errorMsg = 'CRITICAL: harvest_id is empty or missing in API payload. Record cannot be synced without an ID.';
            console.error('[postProductionHarvestRecord] ' + errorMsg);
            console.error('[postProductionHarvestRecord] Payload details:', JSON.stringify(apiPayload, null, 2));
            return {
                success: false,
                status: 400,
                remoteData: errorMsg,
                validationError: true
            };
        }

        const response = await ApiService.post(endpoint, apiPayload);
        console.log('[postProductionHarvestRecord] ✅ Production harvest created successfully with ID:', apiPayload.harvest_id);

        // Log to persistent sync log
        await addSyncLog('productionHarvestService', 'POST', 'SUCCESS',
            `Successfully created harvest ${apiPayload.harvest_id}`,
            { harvest_id: apiPayload.harvest_id, status: response.status }
        );

        // Log activity for successful harvest creation
        try {
            const workerName = apiPayload.worker_name || 'Unknown';
            const weight = apiPayload.weight_on_delivery || 0;
            await logProductionHarvestCreated(response.data.harvest_id || 'N/A', workerName, weight);
        } catch (activityError) {
            console.warn('[postProductionHarvestRecord] Failed to log activity:', activityError);
        }

        return { success: true, status: response.status, remoteData: response.data };
    } catch (error) {
        // Return 0 for status if network error (offline) to handle offline state robustly
        const status = error.response ? error.response.status : 0;
        const remoteData = error.response ? error.response.data : (error.message || 'Network Error');
        const errorMsg = typeof remoteData === 'string' ? remoteData : JSON.stringify(remoteData);

        // Log to persistent sync log for later debugging
        await addSyncLog('productionHarvestService', 'POST', 'ERROR',
            `Failed to create harvest ${apiPayload.harvest_id}`,
            {
                harvest_id: apiPayload.harvest_id,
                status: status,
                error_message: errorMsg.substring(0, 200),
            }
        );

        // Log CRITICAL ERROR with visual separation so it's visible (not buried in HTML)
        console.error('\n\n');
        console.error('╔════════════════════════════════════════════════════════════╗');
        console.error('║ ❌ POST REQUEST FAILED - CRITICAL ERROR                   ║');
        console.error('╠════════════════════════════════════════════════════════════╣');
        console.error(`║ Status Code: ${status}`);
        console.error(`║ Harvest ID: ${apiPayload.harvest_id || 'MISSING'}`);
        console.error(`║ Worker: ${apiPayload.worker_name || 'Unknown'}`);
        console.error('╠════════════════════════════════════════════════════════════╣');
        console.error('║ Error Summary:');
        // Only show first 150 chars to avoid HTML dump
        const shortError = errorMsg.substring(0, 150).replace(/\n/g, ' ');
        console.error(`║ ${shortError}`);
        console.error('╚════════════════════════════════════════════════════════════╝');
        console.error('\n\n');

        // Full details for debugging if needed
        console.error('[postProductionHarvestRecord] Full error details:', {
            harvestId: apiPayload.harvest_id,
            workerName: apiPayload.worker_name,
            status: status,
            endpoint: endpoint
        });

        return { success: false, status: status, remoteData: remoteData };
    }
};

/**
 * Fetches a list of all production harvest records from the API.
 */
export const fetchAllProductionHarvestRecords = async () => {
    // Endpoint: harvests/ (production harvests from the harvests app)
    const endpoint = 'harvests/';

    try {
        const response = await ApiService.get(endpoint);
        console.log('[fetchAllProductionHarvestRecords] Raw response.data:', JSON.stringify(response.data, null, 2));
        console.log('[fetchAllProductionHarvestRecords] response.data keys:', Object.keys(response.data || {}));
        console.log('[fetchAllProductionHarvestRecords] response.data.results:', JSON.stringify(response.data?.results, null, 2));

        return { success: true, status: response.status, remoteData: response.data };
    } catch (error) {
        const status = error.response ? error.response.status : 0;
        const remoteData = error.response ? error.response.data : (error.message || 'Network Error');
        console.error('[fetchAllProductionHarvestRecords] Error:', error.message, remoteData);
        return { success: false, status: status, remoteData: remoteData };
    }
};

/**
 * Fetches a single production harvest record by its harvest_id.
 * @param {string} harvestId - The harvest_id (primary key) of the harvest record to fetch.
 */
export const fetchProductionHarvestRecordById = async (harvestId) => {
    // API uses harvest_id as the path parameter: harvests/{harvest_id}/
    const endpoint = `harvests/${harvestId}/`;

    try {
        const response = await ApiService.get(endpoint);
        return { success: true, status: response.status, remoteData: response.data };
    } catch (error) {
        const status = error.response ? error.response.status : 0;
        const remoteData = error.response ? error.response.data : (error.message || 'Network Error');
        return { success: false, status: status, remoteData: remoteData };
    }
};

/**
 * Handles the DELETE request to remove a production harvest record.
 * @param {string} harvestId - The harvest_id of the harvest record to delete.
 */
export const deleteProductionHarvestRecord = async (harvestId) => {
    const endpoint = `harvests/${harvestId}/`;

    try {
        const response = await ApiService.delete(endpoint);
        return { success: true, status: response.status, remoteData: response.data };
    } catch (error) {
        const status = error.response ? error.response.status : 0;
        const remoteData = error.response ? error.response.data : (error.message || 'Network Error');

        console.error('[deleteProductionHarvestRecord] Error details:', {
            status,
            remoteData,
            endpoint,
            harvestId
        });

        return { success: false, status: status, remoteData: remoteData };
    }
};

/**
 * Handles the PUT request to update an existing production harvest record.
 * @param {string} harvestId - The harvest_id of the harvest record to update.
 * @param {object} uiPayload - The UI payload containing updated harvest data.
 */
export const updateProductionHarvestRecord = async (harvestId, uiPayload) => {
    const apiPayload = mapToApiPayload(uiPayload);
    const endpoint = `harvests/${harvestId}/`;

    console.log('[updateProductionHarvestRecord] Attempting to UPDATE record:', harvestId);
    console.log('[updateProductionHarvestRecord] Original UI payload:', uiPayload);
    console.log('[updateProductionHarvestRecord] Mapped API payload:', apiPayload);

    try {
        // Validate ID before sending
        if (!harvestId) {
            const errorMsg = 'CRITICAL: harvestId is empty. Cannot update record without ID.';
            console.error('[updateProductionHarvestRecord] ' + errorMsg);
            return {
                success: false,
                status: 400,
                remoteData: errorMsg,
                validationError: true
            };
        }

        const response = await ApiService.put(endpoint, apiPayload);
        console.log('[updateProductionHarvestRecord] ✅ Record updated successfully:', harvestId);
        return { success: true, status: response.status, remoteData: response.data };
    } catch (error) {
        const status = error.response ? error.response.status : 0;
        const remoteData = error.response ? error.response.data : (error.message || 'Network Error');
        const errorMsg = typeof remoteData === 'string' ? remoteData : JSON.stringify(remoteData);

        // Log CRITICAL ERROR with visual separation so it's visible (not buried in HTML)
        console.error('\n\n');
        console.error('╔════════════════════════════════════════════════════════════╗');
        console.error('║ ❌ PUT REQUEST FAILED - CRITICAL ERROR                    ║');
        console.error('╠════════════════════════════════════════════════════════════╣');
        console.error(`║ Status Code: ${status}`);
        console.error(`║ Harvest ID: ${harvestId || 'MISSING'}`);
        console.error(`║ Endpoint: ${endpoint}`);
        console.error('╠════════════════════════════════════════════════════════════╣');
        console.error('║ Error Summary:');
        // Only show first 150 chars to avoid HTML dump
        const shortError = errorMsg.substring(0, 150).replace(/\n/g, ' ');
        console.error(`║ ${shortError}`);
        console.error('╚════════════════════════════════════════════════════════════╝');
        console.error('\n\n');

        // Full details for debugging if needed
        console.error('[updateProductionHarvestRecord] Full error details:', {
            harvestId: harvestId,
            endpoint: endpoint,
            status: status
        });

        return { success: false, status: status, remoteData: remoteData };
    }
};


// --- OFFLINE SYNC UTILITIES ---

/**
 * Retrieves all unsynced production harvest records from local storage queue.
 */
export const getUnsyncedProductionRecords = async () => {
    try {
        const raw = await AsyncStorage.getItem(SYNC_QUEUE_KEY);
        const records = raw ? JSON.parse(raw) : [];
        return { success: true, records };
    } catch (error) {
        console.error("Error retrieving unsynced production records:", error);
        return { success: false, records: [] };
    }
};

/**
 * Removes a record from the local queue after a successful sync.
 * @param {string} localId - The unique local ID of the record to remove.
 */
export const removeProductionRecordFromQueue = async (localId) => {
    try {
        const { records: currentQueue } = await getUnsyncedProductionRecords();

        // Filter out the record matching the localId
        const newQueue = currentQueue.filter(record => record.id !== localId);

        await AsyncStorage.setItem(SYNC_QUEUE_KEY, JSON.stringify(newQueue));
        return { success: true, remaining: newQueue.length };

    } catch (error) {
        console.error("Error removing production record from queue:", error);
        return { success: false, remaining: -1 };
    }
};

/**
 * Tries to sync all locally saved production records to the remote API.
 * This is the main function to call when connectivity is restored.
 */
export const syncAllProductionRecords = async () => {
    console.log(`\n╔════════════════════════════════════════════════════════════╗`);
    console.log(`║ STARTING PRODUCTION HARVEST SYNC                          ║`);
    console.log(`╚════════════════════════════════════════════════════════════╝\n`);

    const { success, records } = await getUnsyncedProductionRecords();
    if (!success || records.length === 0) {
        console.log('[syncAllProductionRecords] ℹ️  No records to sync');
        console.log(`\n╔════════════════════════════════════════════════════════════╗`);
        console.log(`║ SYNC SKIPPED - NO PENDING RECORDS                         ║`);
        console.log(`╚════════════════════════════════════════════════════════════╝\n`);
        return { syncedCount: 0, totalCount: 0, failedRecords: [] };
    }

    let syncedCount = 0;
    const totalCount = records.length;
    const failedRecords = [];

    console.log(`[syncAllProductionRecords] Found ${totalCount} record(s) waiting to sync`);
    console.log(`[syncAllProductionRecords] Sync queue contents:`);
    records.forEach((record, index) => {
        console.log(`  ${index + 1}. ID: ${record.id || 'MISSING'} | Worker: ${record.workerName || 'Unknown'}`);
    });

    // Use a deep copy to iterate over, in case the queue is modified during iteration
    for (const record of records) {
        console.log(`[syncAllProductionRecords] Processing record ${record.id}:`, JSON.stringify(record, null, 2));

        // Validate required fields before attempting sync
        const validationErrors = [];

        // Critical: Harvest ID is REQUIRED for all records (either from local id or harvest_id field)
        if (!record.id && !record.harvest_id) {
            validationErrors.push(`Harvest ID is missing (neither id nor harvest_id found)`);
        }

        if (!record.paidBy && !record.paid_by && !record.who_paid) {
            validationErrors.push(`paidBy is missing`);
        }

        if (!record.workerName && !record.worker_name && !record.name) {
            validationErrors.push(`workerName is missing`);
        }

        if (!record.blockId && !record.block_id && !record.block) {
            validationErrors.push(`blockId is missing`);
        }

        if (!record.date) {
            validationErrors.push(`date is missing`);
        }

        if (!record.weight && record.weight !== 0) {
            validationErrors.push(`weight is missing`);
        }

        if (validationErrors.length > 0) {
            console.warn(`[syncAllProductionRecords] Skipping record ${record.id}: ${validationErrors.join(', ')}`);
            failedRecords.push({ id: record.id, reason: validationErrors.join(', ') });
            continue;
        }

        // Try to POST the record. If it already exists (409 or 405), use PUT instead
        console.log(`\n[syncAllProductionRecords] ──────────────────────────────────────────`);
        console.log(`[syncAllProductionRecords] Step 1️⃣: Attempting POST to create new record...`);
        console.log(`[syncAllProductionRecords] Record ID: ${record.id || 'MISSING'}`);
        let response = await postProductionHarvestRecord(record);

        // If POST fails with 405 or 409 (conflict/method not allowed), try PUT (update)
        if (!response.success && (response.status === 405 || response.status === 409)) {
            console.log(`[syncAllProductionRecords] ⚠️  POST failed with status ${response.status} (conflict detected)`);
            console.log(`[syncAllProductionRecords] Step 2️⃣: Record already exists on backend, attempting PUT (update)...`);
            response = await updateProductionHarvestRecord(record.id, record);
        }

        if (response.success) {
            // If successful, remove the record from the local queue
            console.log(`[syncAllProductionRecords] ✅ Step 3️⃣: SYNC SUCCESS - Record ${record.id} synced successfully!`);
            console.log(`[syncAllProductionRecords] Removing from sync queue...`);
            await removeProductionRecordFromQueue(record.id);
            syncedCount++;
            console.log(`[syncAllProductionRecords] ──────────────────────────────────────────\n`);
        } else {
            // Failed (either offline or API issue). Leave it in the queue for the next sync attempt.
            console.error(`[syncAllProductionRecords] ❌ SYNC FAILED for record ${record.id}`);
            console.error(`[syncAllProductionRecords] Status Code: ${response.status}`);
            console.error(`[syncAllProductionRecords] Error Details:`, response.remoteData);
            if (response.validationError) {
                console.error(`[syncAllProductionRecords] ⚠️  VALIDATION ERROR - Check record data integrity`);
            }
            console.error(`[syncAllProductionRecords] Record left in queue for retry`);
            console.log(`[syncAllProductionRecords] ──────────────────────────────────────────\n`);
            failedRecords.push({
                id: record.id,
                status: response.status,
                error: response.remoteData,
                validationError: response.validationError || false
            });
        }
    }

    console.log(`\n╔════════════════════════════════════════════════════════════╗`);
    console.log(`║ SYNC COMPLETE                                              ║`);
    console.log(`╠════════════════════════════════════════════════════════════╣`);
    console.log(`║ Total Records: ${totalCount}`);
    console.log(`║ Successfully Synced: ${syncedCount} ✅`);
    console.log(`║ Failed: ${failedRecords.length} ${failedRecords.length > 0 ? '❌' : ''}`);
    console.log(`╚════════════════════════════════════════════════════════════╝\n`);

    if (failedRecords.length > 0) {
        console.error(`[syncAllProductionRecords] FAILED RECORDS DETAILS:`);
        failedRecords.forEach((record, index) => {
            console.error(`  ${index + 1}. ID: ${record.id}`);
            console.error(`     Status: ${record.status}`);
            if (record.validationError) {
                console.error(`     Issue: VALIDATION ERROR - Payload problem`);
            } else if (record.reason) {
                console.error(`     Reason: ${record.reason}`);
            } else {
                console.error(`     Error: ${typeof record.error === 'string' ? record.error.substring(0, 100) : 'See details above'}`);
            }
        });
    }

    // Log sync completion activity
    if (syncedCount > 0) {
        try {
            await logSyncCompleted(syncedCount, totalCount);
        } catch (activityError) {
            console.warn('[syncAllProductionRecords] Failed to log sync activity:', activityError);
        }
    }

    return { syncedCount, totalCount, failedRecords };
};
